import "./globals.css";
import Navbar from "./components/Navbar";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "NutriGuide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
