import "./globals.css";
import Navbar from "./components/Navbar";
import SessionWrapper from "./components/SessionWrapper";

export const metadata = {
  title: "NutriGuide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <SessionWrapper>{children}</SessionWrapper>
      </body>
    </html>
  );
}
